### ISSUE TITLE
Customizable extraction directories?

### ISSUE THREAD

**Issue by tehroot** [leafac/caxa#38]
Is there a reason that you rely strictly on leveraging mktemp or os.tempdir?

This poses issues when the /tmp mount is set to noexec, and it also has issues because of selinux policy issues with /tmp as well. 

Is there a reason that this is default non modifiable behavior? 

I would be more than happy to write a small update that allows customizable paths for extraction locations but I'm not sure if there's a reason you specifically do that before I spend time on it

**Comment by leafac** [comment]
@tehroot Thanks for reaching out.

I went with the temporary directory because I knew it would clean up after itself so you don’t end up with many old versions of caxa-packaged applications laying around. But you’re right that this comes with some drawbacks. Most alarmingly, some operating systems clean the temporary directory in the middle of operation, not only between boots.

You’re also right that this has come up before and it’ll be address in upcoming versions of caxa. So I’m closing this in favor of the other issues that cover the same idea. Please continue the conversation over there.

Best.
