### ISSUE TITLE
How to add logs to exe made with caxa

### ISSUE THREAD

**Issue by sutarsohan77** [leafac/caxa#41]
I want to execute below command with caxa -
 "node index.js > logs.txt"

**Comment by portothree** [comment]
Hey @sutarsohan77, if I get this right, you want to write the output (logs, errors, etc) to the `logs.txt` file, why don't you use something like winston to manage logging in node?

In my understanding, `caxa` is just a wrapper to run node in environments where node is not present, in your case, the command need to run in a shell to send the stdout stream to the logs.txt file (`>`).

Why don't you just create the following shell script?
```sh
node index.js 2>&1 logs.txt
```

`2>&1` will ensure stderr are also redirected to the file

**Comment by leafac** [comment]
@sutarsohan77: First of all, thanks for using caxa and for reaching out.

I don’t think you should do this redirection of the output to a file with the invocation of caxa. Reasons:

1. caxa doesn’t support it. When you write something like "{{caxa}}>" it’s going to be interpreted as a file with that name, not as a ">" that would redirect output. The command that you give to caxa to execute isn’t even interpreted by a shell—caxa just directly invokes your program.

2. It probably breaks users’ expectations. Typically users expect to have the output of commands on the standard output, and expect to be able to redirect that output to where it makes more sense for them: a file, a log processor such as journalctl, and so forth.

3. In the example command you include "{{caxa}}logs.txt" as the file where the logs would be written to. Typically you shouldn’t be writing to the "{{caxa}}" directory from your application. That’s a temporary directory on which your application code is extracted. It’s like a cache. So it could be removed by the operating system. And it can be difficult for users to even find that direction to consult the logs.

I recommend that instead you add some option for output redirection in your application itself. For example, the ‘--output <filename>’ or ‘-O <filename>’ options that you’d find in tools like curl. Or, if you don’t want to users that option, you can always just replace console.log() with something that writes logs to files.

---

@portothree: Thanks for the insightful comment. I agree with what you proposed (as may notice from my answer above).

**Comment by unphased** [comment]
I don't think the title of this issue is great but I think my question is related enough to ask here. 

My understanding is that the caxa selfextracting executable would preserve cwd while it runs. this should mean that if I run something like `fs.writeFileSync("file", content)` that content would land in a file named `file` in the same dir that the caxa self extracting executable *was run from*. 

From my testing on windows it does seem to be able to open files correctly from the cwd but my code uses the following to determine an output location, which works fine when i run my code via `node --loader ts-node/esm` 

```
import { fileURLToPath } from 'url';
import { dirname, basename } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
fs.writeFileSync(path.join(__dirname, "output"), content);
```

but when this is being run from caxa it is pretty clearly going to cause my output files to be dropped in the hidden temp folder that caxa code executes from ... 

This is actually reasonable behavior and this rubber 🦆 session got me where I needed to be but I figured it's worth pointing out that `__dirname` has potential pitfalls with this.
