### ISSUE TITLE
Feature request: file for exclusions, configuration file

### ISSUE THREAD

**Issue by jeffrson** [leafac/caxa#55]
Hi,

because I cannot clean up my working directory (remove .git a.s.o.) I have rather many "-e" parameters.

It would be great, if caxa could support something like .caxaignore, in order to avoid those numerous "-e" parameters.

Also a configuration file would be nice, because command lines become rather long, if, say, you don't want to include node, don't want to dedupe, have prepare command and long special start commands.

Thanks

**Comment by leafac** [comment]
Hi @jeffrson,

Thanks for reaching out.

I don’t see much of an issue with having many `-e` parameters, or having a long command line in general. You may, for example, put that command line in `package.json` under `scripts` and it effectively becomes a “configuration file” for caxa. That’s [how I use caxa](https://github.com/courselore/courselore/blob/387512a00b5e59a8346153f0e5416bd265ec0e25/.github/workflows/main.yml#L21), for example.

Alternatively, you may use caxa from Node.js instead of the command line. Start by `import caxa from "caxa";` and then [take a look at the arguments you may pass](https://github.com/leafac/caxa/blob/5576fce37065ae06d7f1da3e2bceec13a9f433f9/source/index.ts#L14-L62). This allows for even more sophisticated features that aren’t available on the command line, for example, passing a function as a filter of files to exclude. And, again, a `caxa.js` file in your home folder can pass as a “configuration file.” Using a sort JavaScript program as a configuration file is a practice you’ll find in many tools, for example, webpack & Gatsby.

And if you really want a `.caxaignore`, then your little `caxa.js` script may read it and parse it.

With all these options on the table, I don’t see a point of adding support for a `.caxaignore`, so I’ll close the issue.

Thanks again for reaching out 😁
