### ISSUE TITLE
caxa with adonisJs It doesn't work for me can you help please!!

### ISSUE THREAD

**Issue by biloo-dev** [leafac/caxa#57]
I have an AdonisJS project and I want to package it for windows. exe
I tried with this command : 
`npx caxa --input "./build/" --output "adonis.exe" -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/server.js"`
 but not work 

this is my project repo

**Comment by leafac** [comment]
Hi @biloo-dev,

Thanks for reaching out. Can you please provide more information? What didn’t work? What kinds of error messages did you see?

**Comment by biloo-dev** [comment]
When I build my project (from ts to js).
I wanted to package it as an .exe file. No error was received, but the console screen stayed for a while and then disappeared, and the server did not start

**Comment by leafac** [comment]
I’m afraid I don’t have enough information to help you. If the error is happening on TypeScript → JavaScript compilation then it isn’t related to caxa (TypeScript → JavaScript compilation should happen before you even start using caxa). If the console hung for a while and then returned to the prompt when you were compiling the binary with caxa, then that’s the expected behavior: calling caxa should create a binary, not run it. If you’re trying to run the binary generated by caxa and some other error is happening, it probably has something to do with your application.

I’m closing this issue for now. If you think there’s something we can do from caxa’s side to help you out, please let me know.

Thanks again for reaching out.
