### ISSUE TITLE
"Unsupported 16-Bit Application" error on Windows exe

### ISSUE THREAD

**Issue by bbcom-diego-hernandez** [leafac/caxa#64]
Hello!

Windows fails to run exe files generated by `caxa` with error `Unsupported 16-Bit Application`.

I'm running `caxa` and generating the exe files on Linux, I don't know if this can be reproduced by generating them on macOS. If I generate a sh executable it works fine on Linux, my problem is just with Windows executables.

Information:
- Windows 10 Pro x64 build 19043.1889 (where I'm trying to run the exe file)
- Linux Mint 19.3 Tricia x64 (where I'm generating the exe files with caxa)
- Node.js version: v16.14.2 (running on Linux)
- NPM version: 8.5.0 (running on Linux)
- Caxa version: 2.1.0 (running on Linux)

Steps to reproduce:
1. On Linux, create an empty folder and create an index.js file with a simple console log:
   ```bash
   mkdir test && cd test
   echo 'console.log("Hello from Windows!");' > index.js
   ```
1. Create the exe with caxa:
   ```bash
   caxa --input "." --output "hello-from-windows.exe" -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/index.js"
   ```
1. Move the `hello-from-windows.exe` to Windows and try to execute it

The results that I get:
From Command Prompt:
```
C:\Users\diego>C:\Users\diego\Desktop\hello-from-windows.exe
This version of C:\Users\diego\Desktop\hello-from-windows.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
```
and a info message is displayed with the following message:
```
Unsupported 16-Bit Application
The program or feature "\??C:\Users\diego\Desktop\hello-from-windows.exe" cannot start or run due to incompatibility with 64-bit versions of Windows. Please contact the software vendor or ask if a 64-bit Windows compatible version is available.
```
If I run the exe from PowerShell I get this:
```
PS C:\Users\diego> C:\Users\diego\Desktop\shared\aaaaaaaa\hello-from-windows.exe
Program 'hello-from-windows.exe' failed to run: The specified executable is not a valid application for this OS
platform.At line:1 char:1
+ C:\Users\diego\Desktop\shared\aaaaaaaa\hello-from-windows.exe
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ C:\Users\diego\Desktop\shared\aaaaaaaa\hello-from-windows.exe
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

Please let me know if you have the necessary information to review this issue. I like `caxa` and how flexible it is, I want to use it on my organization to generate stand-alone console apps written on ESM.

Thanks!

**Comment by leafac** [comment]
Hi @bbcom-diego-hernandez,

Thanks for reaching out.

[caxa doesn’t support compiling in Linux to run on Windows](https://github.com/leafac/caxa/tree/6f0a10ef252bd84a937eacb1b3067374db4d6035#why-no-cross-compilation-why-no-different-versions-of-nodejs-besides-the-version-with-which-caxa-was-called).

I’d love for this to work, but it isn’t practical because you may be using native extensions (Node.js packages partially written in C/C++), and the native extensions would need to be compiled for the other operating system as well. It’s a can of worms…

It’s much more reliable and straightforward to build on the operating system you’ll be running. And in most cases you already need a computer with that operating system anyway to test your program.

I hope that helps.

Please feel free to reopen the issue if you think there’s something that still haven’t been addressed.

Best.
