### ISSUE TITLE
 libnode.so.108: cannot open shared object file

### ISSUE THREAD

**Issue by andrelec1** [leafac/caxa#79]
I try with node 16.13.2 and 16.20.0

The build as working before, but look like a didn't change anything.
Now when i package the app, the binarie is only 6Mb ( instead ~30Mb )

The binarie work on my computer, but when i move it into my serveur i have this error:
`/tmp/caxa/applications/xxxx-exec-prod/wwytkn1b3q/0/node_modules/.bin/node: error while loading shared libraries: libnode.so.108: cannot open shared object file: No such file or directory`

But if i copy the node_modules/.bin/ folder from working version into the node_modules/.bin/ the app work !

**Comment by leafac** [comment]
Hi @andrelec1,

Thanks for considering using caxa. I’m not sure what the issue was. Perhaps it had to do with Node.js 16 being too old (at this point it’s no longer maintained).

In any case, I’ve been thinking about the broad strategy employed by caxa and concluded that there is a better way to solve the problem.

It’s a different enough approach that I think it deserves a new name, and it’s part of a bigger toolset that I’m building, which I call [**Radically Straightforward · Package**](https://github.com/radically-straightforward/radically-straightforward/tree/main/package).

I’m deprecating caxa and archiving this repository. I invite you to continue the conversation in [Radically Straightforward’s issues](https://github.com/radically-straightforward/radically-straightforward/issues).

Best.
